services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - ./apps/api/.env
    ports:
      - "8000:8000"
    networks:
      - app-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - ./apps/web/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
