services:
  api:
    volumes:
      - ./apps/api:/src/app
    # Development command (hot reload with fastapi dev)
    command: ["/src/.venv/bin/fastapi", "dev", "/src/app/src/main.py", "--host", "0.0.0.0", "--port", "8000"]

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    command: npm run dev