services:
  api:
    volumes:
      - ./apps/api:/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: npm run dev
